# Generated by Django 5.2 on 2025-04-06 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('type', models.CharField(choices=[('PAYABLE', 'A Pagar'), ('RECEIVABLE', 'A Receber')], db_index=True, max_length=20, verbose_name='Tipo')),
                ('document_number', models.CharField(blank=True, max_length=50, verbose_name='Número do Documento')),
                ('issue_date', models.DateField(verbose_name='Data de Emissão')),
                ('due_date', models.DateField(verbose_name='Data de Vencimento')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Original')),
                ('status', models.CharField(choices=[('OPEN', 'Em Aberto'), ('PAID', 'Paga'), ('OVERDUE', 'Vencida'), ('PARTIALLY_PAID', 'Parcialmente Paga'), ('CANCELED', 'Cancelada')], db_index=True, default='OPEN', max_length=20, verbose_name='Status')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='É Recorrente')),
                ('installment_count', models.IntegerField(blank=True, null=True, verbose_name='Número de Parcelas')),
                ('periodicity_days', models.IntegerField(blank=True, null=True, verbose_name='Periodicidade (Dias)')),
                ('specific_day_month', models.IntegerField(blank=True, null=True, verbose_name='Dia Específico do Mês')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='categories.category', verbose_name='Categoria')),
                ('parent_installment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_installments', to='accounts.account', verbose_name='Parcela Pai')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Conta',
                'verbose_name_plural': 'Contas',
                'ordering': ['due_date'],
            },
        ),
    ]
