# Generated by Django 5.2 on 2025-04-06 15:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='responsible_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='account',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='account',
            name='issue_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de Emissão'),
        ),
        migrations.AlterField(
            model_name='account',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to=settings.AUTH_USER_MODEL, verbose_name='Responsável (Antigo)'),
        ),
    ]
