# Generated by Django 5.2 on 2025-04-06 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responsibles', '0001_initial'),
        ('accounts', '0002_add_responsible_name_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='related_responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='related_accounts', to='responsibles.responsible', verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='account',
            name='responsible_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Responsável'),
        ),
    ]
