--
-- PostgreSQL database dump
--

-- Dumped from database version 16.8 (Ubuntu 16.8-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.8 (Ubuntu 16.8-0ubuntu0.24.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: financeiro
--

-- *not* creating schema, since initdb creates it


ALTER SCHEMA public OWNER TO financeiro;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: accounts_account; Type: TABLE; Schema: public; Owner: financeiro
--

CREATE TABLE public.accounts_account (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    type character varying(20) NOT NULL,
    document_number character varying(50) NOT NULL,
    issue_date date NOT NULL,
    due_date date NOT NULL,
    description character varying(255) NOT NULL,
    original_amount numeric(15,2) NOT NULL,
    status character varying(20) NOT NULL,
    is_recurring boolean NOT NULL,
    installment_count integer,
    periodicity_days integer,
    specific_day_month integer,
    category_id bigint NOT NULL,
    parent_installment_id bigint,
    responsible_id integer,
    responsible_name character varying(100),
    related_responsible_id bigint
);


ALTER TABLE public.accounts_account OWNER TO financeiro;

--
-- Name: accounts_account_id_seq; Type: SEQUENCE; Schema: public; Owner: financeiro
--

ALTER TABLE public.accounts_account ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_account_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: financeiro
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO financeiro;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: financeiro
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: financeiro
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO financeiro;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: financeiro
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: financeiro
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO financeiro;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: financeiro
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: financeiro
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO financeiro;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: financeiro
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO financeiro;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: financeiro
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: financeiro
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: financeiro
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO financeiro;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: financeiro
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: categories_category; Type: TABLE; Schema: public; Owner: financeiro
--

CREATE TABLE public.categories_category (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    name character varying(100) NOT NULL,
    description text NOT NULL,
    parent_id bigint
);


ALTER TABLE public.categories_category OWNER TO financeiro;

--
-- Name: categories_category_id_seq; Type: SEQUENCE; Schema: public; Owner: financeiro
--

ALTER TABLE public.categories_category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categories_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: financeiro
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO financeiro;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: financeiro
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: financeiro
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO financeiro;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: financeiro
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: financeiro
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO financeiro;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: financeiro
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: financeiro
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO financeiro;

--
-- Name: payments_payment; Type: TABLE; Schema: public; Owner: financeiro
--

CREATE TABLE public.payments_payment (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    payment_date date NOT NULL,
    payment_location character varying(100) NOT NULL,
    amount_paid numeric(15,2) NOT NULL,
    account_id bigint NOT NULL
);


ALTER TABLE public.payments_payment OWNER TO financeiro;

--
-- Name: payments_payment_id_seq; Type: SEQUENCE; Schema: public; Owner: financeiro
--

ALTER TABLE public.payments_payment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payments_payment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payments_receipt; Type: TABLE; Schema: public; Owner: financeiro
--

CREATE TABLE public.payments_receipt (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    receipt_date date NOT NULL,
    receipt_location character varying(100) NOT NULL,
    amount_received numeric(15,2) NOT NULL,
    interest numeric(15,2) NOT NULL,
    account_id bigint NOT NULL
);


ALTER TABLE public.payments_receipt OWNER TO financeiro;

--
-- Name: payments_receipt_id_seq; Type: SEQUENCE; Schema: public; Owner: financeiro
--

ALTER TABLE public.payments_receipt ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payments_receipt_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: responsibles_responsible; Type: TABLE; Schema: public; Owner: financeiro
--

CREATE TABLE public.responsibles_responsible (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    name character varying(100) NOT NULL,
    email character varying(254),
    phone character varying(20),
    notes text,
    is_active boolean NOT NULL
);


ALTER TABLE public.responsibles_responsible OWNER TO financeiro;

--
-- Name: responsibles_responsible_id_seq; Type: SEQUENCE; Schema: public; Owner: financeiro
--

ALTER TABLE public.responsibles_responsible ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.responsibles_responsible_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: accounts_account; Type: TABLE DATA; Schema: public; Owner: financeiro
--

COPY public.accounts_account (id, created_at, updated_at, type, document_number, issue_date, due_date, description, original_amount, status, is_recurring, installment_count, periodicity_days, specific_day_month, category_id, parent_installment_id, responsible_id, responsible_name, related_responsible_id) FROM stdin;
\.


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: financeiro
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: financeiro
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: financeiro
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add Conta	7	add_account
26	Can change Conta	7	change_account
27	Can delete Conta	7	delete_account
28	Can view Conta	7	view_account
29	Can add Categoria	8	add_category
30	Can change Categoria	8	change_category
31	Can delete Categoria	8	delete_category
32	Can view Categoria	8	view_category
33	Can add Pagamento	9	add_payment
34	Can change Pagamento	9	change_payment
35	Can delete Pagamento	9	delete_payment
36	Can view Pagamento	9	view_payment
37	Can add Recebimento	10	add_receipt
38	Can change Recebimento	10	change_receipt
39	Can delete Recebimento	10	delete_receipt
40	Can view Recebimento	10	view_receipt
41	Can add Responsável	11	add_responsible
42	Can change Responsável	11	change_responsible
43	Can delete Responsável	11	delete_responsible
44	Can view Responsável	11	view_responsible
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: financeiro
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
1	pbkdf2_sha256$1000000$LvOMlVyJv6F4jC06gZEWMM$k5YkcCstOqaLjchatSSprnxiIbXXhBoO68x3pa3hza8=	2025-05-03 13:13:27.313719-03	t	gabriellozorio			gabriel.lozorio16@gmail.com	t	t	2025-05-03 13:12:52.395405-03
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: financeiro
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: financeiro
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: categories_category; Type: TABLE DATA; Schema: public; Owner: financeiro
--

COPY public.categories_category (id, created_at, updated_at, name, description, parent_id) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: financeiro
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: financeiro
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	accounts	account
8	categories	category
9	payments	payment
10	payments	receipt
11	responsibles	responsible
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: financeiro
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	responsibles	0001_initial	2025-05-03 13:09:20.954517-03
2	contenttypes	0001_initial	2025-05-03 13:09:20.971142-03
3	auth	0001_initial	2025-05-03 13:09:21.113216-03
4	categories	0001_initial	2025-05-03 13:09:21.147085-03
5	accounts	0001_initial	2025-05-03 13:09:21.215793-03
6	accounts	0002_add_responsible_name_field	2025-05-03 13:09:21.278868-03
7	accounts	0003_account_related_responsible_and_more	2025-05-03 13:09:21.317036-03
8	admin	0001_initial	2025-05-03 13:09:21.359337-03
9	admin	0002_logentry_remove_auto_add	2025-05-03 13:09:21.372184-03
10	admin	0003_logentry_add_action_flag_choices	2025-05-03 13:09:21.390334-03
11	contenttypes	0002_remove_content_type_name	2025-05-03 13:09:21.420583-03
12	auth	0002_alter_permission_name_max_length	2025-05-03 13:09:21.449015-03
13	auth	0003_alter_user_email_max_length	2025-05-03 13:09:21.473353-03
14	auth	0004_alter_user_username_opts	2025-05-03 13:09:21.492715-03
15	auth	0005_alter_user_last_login_null	2025-05-03 13:09:21.513094-03
16	auth	0006_require_contenttypes_0002	2025-05-03 13:09:21.515169-03
17	auth	0007_alter_validators_add_error_messages	2025-05-03 13:09:21.534663-03
18	auth	0008_alter_user_username_max_length	2025-05-03 13:09:21.556519-03
19	auth	0009_alter_user_last_name_max_length	2025-05-03 13:09:21.590726-03
20	auth	0010_alter_group_name_max_length	2025-05-03 13:09:21.615842-03
21	auth	0011_update_proxy_permissions	2025-05-03 13:09:21.63621-03
22	auth	0012_alter_user_first_name_max_length	2025-05-03 13:09:21.652065-03
23	payments	0001_initial	2025-05-03 13:09:21.723518-03
24	sessions	0001_initial	2025-05-03 13:09:21.745678-03
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: financeiro
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
9jsbgr3d41e8a6g5boh9vle1buh6kejz	.eJxVjEEOwiAQRe_C2hCgFAaX7j1DM8NMpWpoUtqV8e7apAvd_vfef6kBt7UMW5NlmFidlVWn340wP6TugO9Yb7POc12XifSu6IM2fZ1ZnpfD_Tso2Mq3HkkS2jQGYUoAEIl6NtZZ6WMH3nMHBiXk1AWw0QVAN6L1TlhMYPLq_QHthTfh:1uBFUV:acFSkaa7BDraRH7bT0IBog7vhJDorC4NYrOhHHa94So	2025-05-17 13:13:27.316188-03
\.


--
-- Data for Name: payments_payment; Type: TABLE DATA; Schema: public; Owner: financeiro
--

COPY public.payments_payment (id, created_at, updated_at, payment_date, payment_location, amount_paid, account_id) FROM stdin;
\.


--
-- Data for Name: payments_receipt; Type: TABLE DATA; Schema: public; Owner: financeiro
--

COPY public.payments_receipt (id, created_at, updated_at, receipt_date, receipt_location, amount_received, interest, account_id) FROM stdin;
\.


--
-- Data for Name: responsibles_responsible; Type: TABLE DATA; Schema: public; Owner: financeiro
--

COPY public.responsibles_responsible (id, created_at, updated_at, name, email, phone, notes, is_active) FROM stdin;
\.


--
-- Name: accounts_account_id_seq; Type: SEQUENCE SET; Schema: public; Owner: financeiro
--

SELECT pg_catalog.setval('public.accounts_account_id_seq', 1, false);


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: financeiro
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: financeiro
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: financeiro
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 44, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: financeiro
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: financeiro
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 1, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: financeiro
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: categories_category_id_seq; Type: SEQUENCE SET; Schema: public; Owner: financeiro
--

SELECT pg_catalog.setval('public.categories_category_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: financeiro
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: financeiro
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 11, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: financeiro
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 24, true);


--
-- Name: payments_payment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: financeiro
--

SELECT pg_catalog.setval('public.payments_payment_id_seq', 1, false);


--
-- Name: payments_receipt_id_seq; Type: SEQUENCE SET; Schema: public; Owner: financeiro
--

SELECT pg_catalog.setval('public.payments_receipt_id_seq', 1, false);


--
-- Name: responsibles_responsible_id_seq; Type: SEQUENCE SET; Schema: public; Owner: financeiro
--

SELECT pg_catalog.setval('public.responsibles_responsible_id_seq', 1, false);


--
-- Name: accounts_account accounts_account_pkey; Type: CONSTRAINT; Schema: public; Owner: financeiro
--

ALTER TABLE ONLY public.accounts_account
    ADD CONSTRAINT accounts_account_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: financeiro
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: financeiro
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: financeiro
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: financeiro
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: financeiro
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: financeiro
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: financeiro
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: financeiro
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: financeiro
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: financeiro
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: financeiro
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: financeiro
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: categories_category categories_category_pkey; Type: CONSTRAINT; Schema: public; Owner: financeiro
--

ALTER TABLE ONLY public.categories_category
    ADD CONSTRAINT categories_category_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: financeiro
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: financeiro
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: financeiro
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: financeiro
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: financeiro
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: payments_payment payments_payment_pkey; Type: CONSTRAINT; Schema: public; Owner: financeiro
--

ALTER TABLE ONLY public.payments_payment
    ADD CONSTRAINT payments_payment_pkey PRIMARY KEY (id);


--
-- Name: payments_receipt payments_receipt_pkey; Type: CONSTRAINT; Schema: public; Owner: financeiro
--

ALTER TABLE ONLY public.payments_receipt
    ADD CONSTRAINT payments_receipt_pkey PRIMARY KEY (id);


--
-- Name: responsibles_responsible responsibles_responsible_pkey; Type: CONSTRAINT; Schema: public; Owner: financeiro
--

ALTER TABLE ONLY public.responsibles_responsible
    ADD CONSTRAINT responsibles_responsible_pkey PRIMARY KEY (id);


--
-- Name: accounts_account_category_id_e512e750; Type: INDEX; Schema: public; Owner: financeiro
--

CREATE INDEX accounts_account_category_id_e512e750 ON public.accounts_account USING btree (category_id);


--
-- Name: accounts_account_parent_installment_id_4293905f; Type: INDEX; Schema: public; Owner: financeiro
--

CREATE INDEX accounts_account_parent_installment_id_4293905f ON public.accounts_account USING btree (parent_installment_id);


--
-- Name: accounts_account_related_responsible_id_38fe24ad; Type: INDEX; Schema: public; Owner: financeiro
--

CREATE INDEX accounts_account_related_responsible_id_38fe24ad ON public.accounts_account USING btree (related_responsible_id);


--
-- Name: accounts_account_responsible_id_c28b13b0; Type: INDEX; Schema: public; Owner: financeiro
--

CREATE INDEX accounts_account_responsible_id_c28b13b0 ON public.accounts_account USING btree (responsible_id);


--
-- Name: accounts_account_status_f2a7268d; Type: INDEX; Schema: public; Owner: financeiro
--

CREATE INDEX accounts_account_status_f2a7268d ON public.accounts_account USING btree (status);


--
-- Name: accounts_account_status_f2a7268d_like; Type: INDEX; Schema: public; Owner: financeiro
--

CREATE INDEX accounts_account_status_f2a7268d_like ON public.accounts_account USING btree (status varchar_pattern_ops);


--
-- Name: accounts_account_type_23eb0dc1; Type: INDEX; Schema: public; Owner: financeiro
--

CREATE INDEX accounts_account_type_23eb0dc1 ON public.accounts_account USING btree (type);


--
-- Name: accounts_account_type_23eb0dc1_like; Type: INDEX; Schema: public; Owner: financeiro
--

CREATE INDEX accounts_account_type_23eb0dc1_like ON public.accounts_account USING btree (type varchar_pattern_ops);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: financeiro
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: financeiro
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: financeiro
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: financeiro
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: financeiro
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: financeiro
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: financeiro
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: financeiro
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: financeiro
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: categories_category_parent_id_f141de59; Type: INDEX; Schema: public; Owner: financeiro
--

CREATE INDEX categories_category_parent_id_f141de59 ON public.categories_category USING btree (parent_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: financeiro
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: financeiro
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: financeiro
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: financeiro
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: payments_payment_account_id_af225a32; Type: INDEX; Schema: public; Owner: financeiro
--

CREATE INDEX payments_payment_account_id_af225a32 ON public.payments_payment USING btree (account_id);


--
-- Name: payments_receipt_account_id_dab4f9fb; Type: INDEX; Schema: public; Owner: financeiro
--

CREATE INDEX payments_receipt_account_id_dab4f9fb ON public.payments_receipt USING btree (account_id);


--
-- Name: accounts_account accounts_account_category_id_e512e750_fk_categories_category_id; Type: FK CONSTRAINT; Schema: public; Owner: financeiro
--

ALTER TABLE ONLY public.accounts_account
    ADD CONSTRAINT accounts_account_category_id_e512e750_fk_categories_category_id FOREIGN KEY (category_id) REFERENCES public.categories_category(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_account accounts_account_parent_installment_i_4293905f_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: financeiro
--

ALTER TABLE ONLY public.accounts_account
    ADD CONSTRAINT accounts_account_parent_installment_i_4293905f_fk_accounts_ FOREIGN KEY (parent_installment_id) REFERENCES public.accounts_account(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_account accounts_account_related_responsible__38fe24ad_fk_responsib; Type: FK CONSTRAINT; Schema: public; Owner: financeiro
--

ALTER TABLE ONLY public.accounts_account
    ADD CONSTRAINT accounts_account_related_responsible__38fe24ad_fk_responsib FOREIGN KEY (related_responsible_id) REFERENCES public.responsibles_responsible(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_account accounts_account_responsible_id_c28b13b0_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: financeiro
--

ALTER TABLE ONLY public.accounts_account
    ADD CONSTRAINT accounts_account_responsible_id_c28b13b0_fk_auth_user_id FOREIGN KEY (responsible_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: financeiro
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: financeiro
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: financeiro
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: financeiro
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: financeiro
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: financeiro
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: financeiro
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: categories_category categories_category_parent_id_f141de59_fk_categorie; Type: FK CONSTRAINT; Schema: public; Owner: financeiro
--

ALTER TABLE ONLY public.categories_category
    ADD CONSTRAINT categories_category_parent_id_f141de59_fk_categorie FOREIGN KEY (parent_id) REFERENCES public.categories_category(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: financeiro
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: financeiro
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: payments_payment payments_payment_account_id_af225a32_fk_accounts_account_id; Type: FK CONSTRAINT; Schema: public; Owner: financeiro
--

ALTER TABLE ONLY public.payments_payment
    ADD CONSTRAINT payments_payment_account_id_af225a32_fk_accounts_account_id FOREIGN KEY (account_id) REFERENCES public.accounts_account(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: payments_receipt payments_receipt_account_id_dab4f9fb_fk_accounts_account_id; Type: FK CONSTRAINT; Schema: public; Owner: financeiro
--

ALTER TABLE ONLY public.payments_receipt
    ADD CONSTRAINT payments_receipt_account_id_dab4f9fb_fk_accounts_account_id FOREIGN KEY (account_id) REFERENCES public.accounts_account(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

