# Generated by Django 5.2 on 2025-04-06 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('payment_date', models.DateField(verbose_name='Data de pagamento')),
                ('payment_location', models.CharField(max_length=100, verbose_name='Local de pagamento')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor pago')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.account', verbose_name='Conta')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('receipt_date', models.DateField(verbose_name='Data de recebimento')),
                ('receipt_location', models.CharField(max_length=100, verbose_name='Local de recebimento')),
                ('amount_received', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor recebido')),
                ('interest', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Juros')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='accounts.account', verbose_name='Conta')),
            ],
            options={
                'verbose_name': 'Recebimento',
                'verbose_name_plural': 'Recebimentos',
            },
        ),
    ]
